name: Lint
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set target format file
        run: |
          echo $(git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} --name-only --diff-filter=A -- '*.py')
          echo "TARGET_FORMAT_FILES=`git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} --name-only --diff-filter=A -- '*.py'`" >> $GITHUB_ENV
      - name: check illegal format
        id: check_format
        continue-on-error: true
        uses: psf/black@stable
        with:
          src: $TARGET_FOMRAT_FILES
          options: "--check --verbose"
      - name: exit if no problem format
        run: exit 0
        if: steps.check_format.outcome == 'success'
      - name: set branch suffix
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        if: steps.check_format.outcome == 'failure'
      - name: apply black
        uses: psf/black@stable
        with:
          src: ${{ env.TARGET_FOMRAT_FILES }}
          options: "-q"
        if: steps.check_format.outcome == 'failure'
      - name: commit fix format
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: fix_${{github.head_ref}}_${{ env.CURRENT_DATETIME }}
          message: fix format
          push: true
          add: src
        if: steps.check_format.outcome == 'failure'
      - name: create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: fix_${{github.head_ref}}_${{ env.CURRENT_DATETIME }}
          destination_branch: ${{github.head_ref}}
          pr_title: fix format ${{ env.PR_TITLE }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.check_format.outcome == 'failure'
